# Generated by Django 4.1.3 on 2023-05-06 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_profile_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
